# Generated by Django 4.1.7 on 2023-04-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_datos_empleados_n_empleados_p_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n_empleados_p',
            old_name='nombre',
            new_name='n_emp',
        ),
        migrations.RenameField(
            model_name='n_empleados_p',
            old_name='sector',
            new_name='puesto',
        ),
        migrations.RemoveField(
            model_name='n_empleados_p',
            name='correo',
        ),
    ]
