# Generated by Django 4.1.7 on 2023-04-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0010_login_account_register_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_account',
            name='username',
        ),
        migrations.AddField(
            model_name='register_account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register_account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register_account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='register_account',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register_account',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
