# Generated by Django 4.1.7 on 2023-04-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0011_remove_register_account_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_account',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
