# Generated by Django 4.1.7 on 2023-04-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0012_register_account_username'),
    ]

    operations = []
    
