# Generated by Django 4.1.7 on 2023-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0013_auto_20230419_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos_Empleados',
        ),
        migrations.DeleteModel(
            name='N_Emp_Total',
        ),
        migrations.DeleteModel(
            name='N_Empleados_P',
        ),
        migrations.RemoveField(
            model_name='login_account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login_account',
            name='username',
        ),
        migrations.AlterField(
            model_name='register_account',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
