# Generated by Django 4.1.7 on 2023-04-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0015_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prueba/static/assets/post_images/'),
        ),
    ]
