# Generated by Django 4.1.7 on 2023-04-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0016_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
