# Generated by Django 4.1.7 on 2023-04-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0019_alter_profile_external_link_alter_profile_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
