# Generated by Django 4.1.7 on 2023-04-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0022_alter_register_account_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_account',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
